version: '3'

services:
  nota:
    build: 
      context: ..
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    env_file: 
      - ../.env
    volumes:
      - ../data:/app/data
    depends_on:
      - db
  
  db:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: